Implement dataset frame methods for per-annotation QA
FLIR/conservator-cli pull request #303
Opened 2022-06-17 09:54 UTC by SJLC

Individual annotations for a dataset frame can have same Q/A operations
as the whole dataset frame: approve, request change, edit note explaining
requested change.

2023-01-13 17:44 UTC, nbutler77 requested changes
Please fix merge conflicts. Note that `add_annotations` has been implemented in `main` already (as `add_dataset_annotations`). This new functionality looks good, though it needs integration test cases. Also, please add details of the example code in `docs/usage/examples.rst`

2023-01-19 17:42 UTC, nbutler77 requested changes
Example script should probably:
a) Use new functionality added in this PR
b) Do so with a view towards demonstration, rather than being a usable script

2023-01-19 17:42 UTC, nbutler77 commented on examples/upload_dataset_metadata.py
> +# example of using API to upload annotations and QA status from local copy of dataset
This doesn't seem like a super-useful script. What would be more useful is a script that takes a dataset id, and an arbitrary json file, and e.g. syncs the Conservator annotation QA status with the QA status in the file. Also, the name of this script is misleading, as it does not upload dataset metadata, it only makes some changes to the annotations.

2023-01-26 20:35 UTC, shiftycow commented on examples/dataset_frame_annotation_qa_from_json.py
> +# JSON format
What's the reason for defining this JSON format?

2023-02-01 16:19 UTC, nbutler77 approved these changes
The example script isn't ideal, but everything else looks fine.

2023-02-01 22:56 UTC, merged